[package]
name = "weiroll"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
bitflags = "1"
bytes = "1.4.0"
ethers = "*"
slotmap = "*"
thiserror = "*"
tracing = "*"

[dev-dependencies]
tokio = { version = "1.21", features = ["macros"] }
